sudo: required
dist: trusty
addons:
  apt:
    packages:
      - rsync
      - openssh-client
language: node_js
node_js:
  - "7"
before_install:
    - openssl aes-256-cbc -K $encrypted_d1082e142101_key -iv $encrypted_d1082e142101_iv -in static_pages_key.enc -out static_pages_key -d
    - chmod 0400 static_pages_key
    - eval $(ssh-agent -s)
    - ssh-add static_pages_key
    - mkdir -p ~/.ssh
    - echo -e "Host *\n\tStrictHostKeyChecking no\n\n" > ~/.ssh/config
install:
    - npm install
script:
    - npm test
after_script:
    - rsync -av $TRAVIS_BUILD_DIR/test/visual/backstop/tests/ static-pages.sr-lab.de@static-pages.sr-lab.de:~/public_html/sratoms/srbreakpoints_github/
    - ssh static-pages.sr-lab.de@static-pages.sr-lab.de "chown static-pages.sr-lab.de:static-pages.sr-lab.de -R ~/public_html/sratoms/srbreakpoints_github/"
